services:
  db:
    image: postgres:13-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: analysis
    ports:
      - "5432:5432"
    volumes:
      - ./data/postgres_data:/var/lib/postgresql/data/
  analysis:
    build: ./analysis
    ports:
      - "9090:9090"
    depends_on:
      - db
    volumes:
      - /file/path/one:/volumes/one
      - /file/path/two:/volumes/two
  web:
    build: ./web
    ports:
      - "9091:9091"
    depends_on:
      - analysis